"""
Models for human-in-the-loop approval system.

This module defines models for approval requests that allow users to review
and approve/reject outputs from non-deterministic agents before proceeding.
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field


class ApprovalRequest(BaseModel):
    """Request for approval of non-deterministic agent output."""

    id: str = Field(..., description="Unique identifier for the approval request")
    job_id: str = Field(..., description="ID of the parent processing job")
    agent_name: str = Field(
        ..., description="Name of the agent that generated this output"
    )
    step_name: str = Field(..., description="Pipeline step name")
    pipeline_step: str = Field(
        ...,
        description="Actual pipeline step name for retry (e.g., 'seo_keywords', 'marketing_brief')",
    )

    # Content to review
    input_data: Dict[str, Any] = Field(
        ..., description="Input that was provided to the agent"
    )
    output_data: Dict[str, Any] = Field(
        ..., description="Output generated by the agent"
    )

    # Approval state
    status: Literal["pending", "approved", "rejected", "modified", "rerun"] = Field(
        default="pending", description="Current approval status"
    )

    # User feedback
    user_comment: Optional[str] = Field(None, description="User's comment or feedback")
    modified_output: Optional[Dict[str, Any]] = Field(
        None, description="Modified output if user edited the content"
    )

    # Retry tracking
    retry_job_id: Optional[str] = Field(
        None, description="Job ID if step was retried after rejection"
    )
    retry_count: int = Field(
        default=0, description="Number of times this step has been retried"
    )

    # Metadata
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    reviewed_at: Optional[datetime] = None
    reviewed_by: Optional[str] = None

    # Context
    confidence_score: Optional[float] = Field(
        None, ge=0.0, le=1.0, description="Agent's confidence in its output (0-1)"
    )
    suggestions: Optional[List[str]] = Field(
        None, description="Suggestions or notes for the reviewer"
    )


class ApprovalResponse(BaseModel):
    """Response to an approval request."""

    approval_id: str
    decision: Literal["approve", "reject", "modify", "rerun"]
    comment: Optional[str] = None
    modified_output: Optional[Dict[str, Any]] = None
    reviewed_by: Optional[str] = None


class ApprovalListItem(BaseModel):
    """Lightweight approval item for list views."""

    id: str
    job_id: str
    agent_name: str
    step_name: str
    pipeline_step: str
    status: Literal["pending", "approved", "rejected", "modified", "rerun"]
    created_at: datetime
    reviewed_at: Optional[datetime] = None
    input_title: Optional[str] = None
    user_id: Optional[str] = None


class PendingApprovalsResponse(BaseModel):
    """Response containing list of pending approvals."""

    approvals: List[ApprovalListItem]
    total: int
    pending: int


class ApprovalDecisionRequest(BaseModel):
    """Request body for making an approval decision."""

    decision: Literal["approve", "reject", "modify", "rerun"] = Field(
        ..., description="Approval decision"
    )
    comment: Optional[str] = Field(
        None, description="Optional comment explaining the decision"
    )
    modified_output: Optional[Dict[str, Any]] = Field(
        None, description="Modified output (required if decision is 'modify')"
    )
    selected_keywords: Optional[Dict[str, List[str]]] = Field(
        None,
        description="Selected keywords for seo_keywords step. Format: {'primary': [...], 'secondary': [...], 'lsi': [...]}. Must include 'main_keyword' field.",
    )
    main_keyword: Optional[str] = Field(
        None,
        description="Main keyword selection for seo_keywords step (required when selecting keywords)",
    )
    reviewed_by: Optional[str] = Field(None, description="Username or ID of reviewer")
    auto_retry: bool = Field(
        default=True, description="Automatically retry step if rejected (default: True)"
    )


class ApprovalSettings(BaseModel):
    """Settings for approval behavior in pipeline."""

    require_approval: bool = Field(
        default=False,
        description="Whether to require approval for non-deterministic outputs",
    )

    approval_agents: List[str] = Field(
        default_factory=lambda: [
            "content_pipeline",
            "article_generation",
            "marketing_brief",
            "seo_keywords",
            "seo_optimization",
            "content_formatting",
            "transcript_preprocessing_approval",
            "blog_post_preprocessing_approval",
            "suggested_links",
            # Social media pipeline steps
            "social_media_marketing_brief",
            "social_media_angle_hook",
            "social_media_post_generation",
        ],
        description="List of agent names that require approval",
    )

    auto_approve_threshold: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="Auto-approve if confidence score is above this threshold",
    )

    timeout_seconds: Optional[int] = Field(
        None, gt=0, description="Timeout for approval (auto-reject if not reviewed)"
    )


class ApprovalStats(BaseModel):
    """Statistics about approvals."""

    total_requests: int
    pending: int
    approved: int
    rejected: int
    modified: int
    rerun: int
    avg_review_time_seconds: Optional[float] = None
    approval_rate: float = Field(..., ge=0.0, le=1.0)


class RetryStepRequest(BaseModel):
    """Request body for retrying a rejected step."""

    guidance: Optional[str] = Field(
        None, description="User guidance/feedback to incorporate into regeneration"
    )
