"""
Helper functions for integrating approval flow into processors.

This module provides utilities to pause processing for human approval
of non-deterministic agent outputs.
"""

import json
import logging
from dataclasses import dataclass
from enum import Enum
from typing import Any, Dict, Optional

from marketing_project.services.approval_manager import get_approval_manager

logger = logging.getLogger(__name__)


class ApprovalStatus(str, Enum):
    """Status of an approval check."""

    NOT_REQUIRED = "not_required"
    AUTO_APPROVED = "auto_approved"
    REQUIRED = "required"


@dataclass
class ApprovalResult:
    """Result of an approval check."""

    status: ApprovalStatus
    approval_id: Optional[str] = None
    job_id: Optional[str] = None
    step_name: Optional[str] = None
    step_number: Optional[int] = None

    @property
    def requires_approval(self) -> bool:
        """Check if approval is required."""
        return self.status == ApprovalStatus.REQUIRED

    @property
    def can_continue(self) -> bool:
        """Check if pipeline can continue."""
        return self.status in (
            ApprovalStatus.NOT_REQUIRED,
            ApprovalStatus.AUTO_APPROVED,
        )


class ApprovalRequiredSentinel:
    """
    Sentinel value to signal that approval is required and pipeline should stop.

    This is used instead of exceptions to signal control flow.
    """

    def __init__(self, approval_result: ApprovalResult):
        self.approval_result = approval_result

    def __repr__(self):
        return (
            f"ApprovalRequiredSentinel(approval_id={self.approval_result.approval_id})"
        )


class ApprovalRequiredException(Exception):
    """
    Exception raised when approval is required and pipeline should stop.

    This signals that the pipeline should complete the current job and wait
    for user approval before continuing.
    """

    def __init__(self, approval_id: str, job_id: str, step_name: str, step_number: int):
        self.approval_id = approval_id
        self.job_id = job_id
        self.step_name = step_name
        self.step_number = step_number
        super().__init__(
            f"Approval required for step {step_number}: {step_name} (approval_id: {approval_id})"
        )


class ApprovalCheckFailedException(Exception):
    """
    Exception raised when approval check fails due to a system error.

    This is a critical error that prevents the pipeline from continuing
    to ensure required approvals are not silently skipped.
    """

    error_code = "APPROVAL_CHECK_FAILED"

    def __init__(self, step_name: str, step_number: int, original_error: Exception):
        self.step_name = step_name
        self.step_number = step_number
        self.original_error = original_error
        self.original_error_type = type(original_error).__name__
        super().__init__(
            f"Approval check failed for step {step_number} ({step_name}). "
            f"This prevents the pipeline from continuing to ensure required approvals are not skipped. "
            f"Original error: {original_error}"
        )


async def check_and_create_approval_request(
    job_id: str,
    agent_name: str,
    step_name: str,
    step_number: int,
    input_data: Dict[str, Any],
    output_data: Dict[str, Any],
    context: Dict[str, Any],
    confidence_score: Optional[float] = None,
    suggestions: Optional[list] = None,
) -> ApprovalResult:
    """
    Check if approval is needed and create approval request if required.

    This function:
    1. Checks if approvals are enabled
    2. Checks if this agent requires approval
    3. Creates an approval request if needed
    4. Saves pipeline context to Redis
    5. Returns ApprovalResult indicating whether approval is required

    Args:
        job_id: ID of the processing job
        agent_name: Name of the agent that generated output
        step_name: Pipeline step name
        step_number: Step number in pipeline
        input_data: Input provided to the agent
        output_data: Output generated by the agent
        context: Accumulated context from previous pipeline steps
        confidence_score: Optional confidence score (0-1)
        suggestions: Optional suggestions for reviewer

    Returns:
        ApprovalResult indicating the approval status. If status is REQUIRED,
        the pipeline should stop and wait for approval.
    """
    # Do not reload from DB on every step — settings are stable for the duration of a job.
    # The worker initialises the manager once from DB at startup; the API reloads on every
    # user-facing request where staleness would actually matter.
    manager = await get_approval_manager(reload_from_db=False)
    settings = manager.settings

    # Check if approvals are enabled
    if not settings.require_approval:
        logger.info(
            f"[APPROVAL] Approvals disabled globally, skipping approval check for {agent_name} in job {job_id}"
        )
        return ApprovalResult(status=ApprovalStatus.NOT_REQUIRED)

    # Check if this agent requires approval
    logger.info(
        f"[APPROVAL] Checking if {agent_name} requires approval. Enabled agents: {settings.approval_agents}, require_approval={settings.require_approval}"
    )
    if agent_name not in settings.approval_agents:
        logger.info(
            f"[APPROVAL] Agent '{agent_name}' not in approval_agents list ({settings.approval_agents}), skipping approval. "
            f"To enable approvals for this step, add '{agent_name}' to the approval_agents list in settings. "
            f"Pipeline will continue without approval."
        )
        return ApprovalResult(status=ApprovalStatus.NOT_REQUIRED)

    logger.info(
        f"[APPROVAL] Agent '{agent_name}' requires approval, creating approval request for job {job_id}..."
    )

    # Create approval request
    approval = await manager.create_approval_request(
        job_id=job_id,
        agent_name=agent_name,
        step_name=step_name,
        input_data=input_data,
        output_data=output_data,
        confidence_score=confidence_score,
        suggestions=suggestions,
        pipeline_step=agent_name,
    )

    logger.info(
        f"[APPROVAL] Created approval request {approval.id} for agent '{agent_name}' (step: {step_name}) in job {job_id}"
    )

    # If auto-approved, return auto-approved status
    if approval.status == "approved":
        logger.info(f"Approval {approval.id} auto-approved, continuing pipeline")
        return ApprovalResult(
            status=ApprovalStatus.AUTO_APPROVED,
            approval_id=approval.id,
            job_id=job_id,
            step_name=step_name,
            step_number=step_number,
        )

    logger.info(
        f"[APPROVAL] Created approval request {approval.id} for {agent_name} in job {job_id}. "
        f"Pipeline will stop and wait for approval."
    )

    # Save pipeline context to Redis for resume
    # Extract original content from input_data if available
    original_content = input_data.get("original_content") or context.get(
        "input_content"
    )
    await manager.save_pipeline_context(
        job_id=job_id,
        context=context,
        step_name=step_name,
        step_number=step_number,
        step_result=output_data,
        original_content=original_content,
    )

    # Return result indicating approval is required
    return ApprovalResult(
        status=ApprovalStatus.REQUIRED,
        approval_id=approval.id,
        job_id=job_id,
        step_name=step_name,
        step_number=step_number,
    )


def extract_confidence_score(agent_output: Any) -> Optional[float]:
    """
    Extract confidence score from agent output if available.

    Many LLM agents return confidence scores in their responses.
    This function attempts to extract them from various formats.

    Args:
        agent_output: Agent output (dict, str, or other)

    Returns:
        Confidence score (0-1) if found, None otherwise
    """
    if isinstance(agent_output, dict):
        # Check common keys
        for key in ["confidence", "confidence_score", "score", "certainty"]:
            if key in agent_output:
                try:
                    score = float(agent_output[key])
                    # Normalize to 0-1 if needed
                    if score > 1.0:
                        score = score / 100.0
                    return max(0.0, min(1.0, score))
                except (ValueError, TypeError):
                    pass

    return None


def prepare_approval_data(
    input_content: Any, output_content: Any, max_length: int = 5000
) -> tuple[Dict[str, Any], Dict[str, Any]]:
    """
    Prepare input and output data for approval display.

    Truncates long content and converts to JSON-serializable format.

    Args:
        input_content: Input content (any type)
        output_content: Output content (any type)
        max_length: Maximum length for string fields

    Returns:
        Tuple of (input_data, output_data) as dicts
    """

    def prepare_dict(data: Any) -> Dict[str, Any]:
        if isinstance(data, dict):
            return {
                k: (
                    v[:max_length] + "..."
                    if isinstance(v, str) and len(v) > max_length
                    else v
                )
                for k, v in data.items()
            }
        elif isinstance(data, str):
            content = data[:max_length] + "..." if len(data) > max_length else data
            return {"content": content}
        else:
            try:
                return {"content": str(data)}
            except Exception:
                return {"content": "<Unable to serialize>"}

    return prepare_dict(input_content), prepare_dict(output_content)
