name: Code Formatting

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  format-check:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        
    - name: Check Black formatting
      run: black --check --diff src/ tests/
      
    - name: Check isort import sorting
      run: isort --check-only --diff src/ tests/
      
    - name: Check Flake8
      run: flake8 src/ tests/
      
    - name: Check MyPy type hints
      run: mypy src/marketing_project/

  auto-format:
    name: Auto-format Code
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        
    - name: Format with Black
      run: black src/ tests/
      
    - name: Sort imports with isort
      run: isort src/ tests/
      
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if ! git diff --staged --quiet; then
          git commit -m "style: auto-format code with black and isort"
          git push
        fi
